networks:
  nucleo-network:
    name: nucleo-network
    external: true

services:
  postgres:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:7432:5432"

  redis:
    image: redis:6.2.6
    ports:
      - "127.0.0.1:6379:6379"

  sequencer:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    entrypoint: /usr/local/bin/nitro
    ports:
      - "127.0.0.1:8547:8547"
      - "127.0.0.1:8548:8548"
      - "127.0.0.1:9642:9642"
    volumes:
      - "seqdata:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
      - "tokenbridge-data:/tokenbridge-data"
    command: --conf.file /config/sequencer_config.json --node.feed.output.enable --node.feed.output.port 9642  --http.api net,web3,eth,txpool,debug --node.seq-coordinator.my-url  ws://sequencer:8548 --graphql.enable --graphql.vhosts * --graphql.corsdomain *
    networks:
      - nucleo-network

  poster:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    entrypoint: /usr/local/bin/nitro
    ports:
      - "127.0.0.1:8147:8547"
      - "127.0.0.1:8148:8548"
    volumes:
      - "poster-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - redis
    networks:
      - nucleo-network

  validator:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    entrypoint: /usr/local/bin/nitro
    ports:
      - "127.0.0.1:8247:8547"
      - "127.0.0.1:8248:8548"
    volumes:
      - "validator-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/validator_config.json --http.port 8547 --http.api net,web3,arb,debug --ws.port 8548
    depends_on:
      - sequencer
      - validation_node
    networks:
      - nucleo-network

  validation_node:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    entrypoint: /usr/local/bin/nitro-val
    ports:
      - "127.0.0.1:8949:8549"
    volumes:
      - "config:/config"
    command: --conf.file /config/validation_node_config.json
    networks:
      - nucleo-network

  scripts:
    build: scripts/
    volumes:
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
      - "tokenbridge-data:/tokenbridge-data"
    networks:
      - nucleo-network

  tokenbridge:
    depends_on:
      - sequencer
    pid: host
    build:
      context: tokenbridge/
      args:
        TOKEN_BRIDGE_BRANCH: ${TOKEN_BRIDGE_BRANCH:-}
    environment:
      - ARB_URL=http://sequencer:8547
      - ETH_URL=http://l1-node:8545
    volumes:
      - "tokenbridge-data:/workspace"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nucleo-network

  rollupcreator:
    depends_on:
      - sequencer
    pid: host
    build:
      context: rollupcreator/
      args:
        NITRO_CONTRACTS_BRANCH: ${NITRO_CONTRACTS_BRANCH:-}
    volumes:
      - "config:/config"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nucleo-network

volumes:
  l1data:
  consensus:
  l1keystore:
  seqdata:
  validator-data:
  poster-data:
  config:
  postgres-data:
  tokenbridge-data:
